services:
  # Postgres
  postgres:
    image: postgres:16
    container_name: knowledge_hub_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
      - ./infra/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: knowledge_hub_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8088:80
    depends_on:
      - postgres

  # MongoDB
  mongodb:
    image: mongo:7
    container_name: knowledge_hub_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - enterprise_agent
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: knowledge_hub_mongodb_express
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}?authSource=admin
    networks:
      - enterprise_agent
    ports:
      - 8081:8081
    depends_on:
      - mongodb

  # Redis
  redis:
    image: redis:7.4.0
    container_name: knowledge_hub_redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - enterprise_agent
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.1
    container_name: knowledge_hub_elasticsearch
    environment:
      - discovery.type=single-node
    networks:
      - enterprise_agent
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

networks:
  enterprise_agent:
    driver: bridge
volumes:
  postgres_data:
  mongodb_data:
  redis_data:
  elasticsearch_data:
  etcd_data:
  minio_data:
  milvus_data:
